### ISSUE TITLE
Support for AmneziaWG protocol

### ISSUE THREAD

**Issue by clinkme4g** [zhsj/wghttp#16]
It's a fork of [WireGuard-Go](https://github.com/WireGuard/wireguard-go) and offers protection against detection by Deep Packet Inspection (DPI) systems, because in some countries standard VPN protocols are totally blocked.
[https://github.com/amnezia-vpn/amneziawg-go](https://github.com/amnezia-vpn/amneziawg-go)

**Comment by zhsj** [comment]
Sorry, I'm not going to support additional protocols. But you're free to fork.
