### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by XEGARE** [zhsj/wghttp#5]
Hello. wghttp started listening on 127.0.0.1:8080. I use PAC file for some sites. But for some reason it is not possible to use the IP of the machine in the local network (192.168.x.x) proxying does not work. --listen=192.168.x.x:8080 will work

Same issue when using in docker. Only localhost is available there, I can’t even specify the address of the machine

**Comment by zhsj** [comment]
You can use `--listen=:8080`, which listens on all interface. But this leaves **security hole** as others on your network can connect to your proxy.
