### ISSUE TITLE
It is low efficiency to use wghttp to convert WireGuard to HTTP or Socket

### ISSUE THREAD

**Issue by Wuqibor** [zhsj/wghttp#6]
My computer: Windows 10.0.19044
Official: Windows desktop client (App: 0.5.3 Driver: 0.10.1)
WGHTTP: latest source build, Go version: 19.1
Test: telecom 200 m broadband in China > WarpPlus (Cloudflare) > managed to Cloudflare CDN (test file: https://cdn.57777777.xyz/1080p.mp4)
Download using the IDM (16 thread)
Only 500k-1.5m speed with WGHTTP and 8-15m /s speed with official client
Maybe the official use of Tun equipment is more efficient. But this difference is quite big. I hope you can think this part

**Comment by zhsj** [comment]
If you can reproduce this by connecting warp from other places expect mainland China, the I can investigate.
