### ISSUE TITLE
Support multiple DNS servers

### ISSUE THREAD

**Issue by JJRcop** [zhsj/wghttp#8]
Currently only supports one, but some VPN providers over WireGuard feature two or more

**Comment by zhsj** [comment]
But why?

**Comment by JJRcop** [comment]
They are used as fallback DNS servers. If one fails the other is used

**Comment by zhsj** [comment]
Why you ever think this is needed? Have you really met that one dns server is down, while the vpn is still working...

**Comment by JJRcop** [comment]
Multiple DNS servers is a feature available in every other network configuration tool I have ever used, I don't see a good reason to not implement it here other than to avoid doing it

**Comment by zhsj** [comment]
You can't just say because others have, while not think about the real needs.

**Comment by JJRcop** [comment]
This feature is necessary because the DNS server is not the same server as the VPN itself. It can go down separately while the VPN server stays up. That's why they have two DNS servers: in case one goes down, the other one stays up and can be used. This is a poor user experience, because you have to change your shell script and replace the DNS server to use the backup, rather than the program handling it for you automatically.

It would cause a major inconvenience to users if the DNS server goes down, so it's a standard practice for most DNS providers to have two.

Google has 8.8.8.8, and 8.8.4.4 as backup. Cloudflare has 1.1.1.1, and 1.0.0.1 as backup. Why are these major companies providing backups if they are not needed?
