### ISSUE TITLE
Proxy in torrent client

### ISSUE THREAD

**Issue by XEGARE** [zhsj/wghttp#9]
Hello.  I want to use **wghttp** as a proxy for **qBitTorrent.**  But when I set an address that **wghttp** is listening on, I don't get connections to peers.  **wghttp** itself throws errors.  I tried _**http**_ and _**socks5**_ protocol in torrent client but the behavior is the same. 

- **wghttp** in docker
- **windows** system
- **qBitTorrent** latest version (on qt6, also tried beta)
- Everything is ok with the connection data itself (I checked it in the **Wireguard** application)

I will run more tests.  I'll tell you exactly what errors I'm getting while I'm asking: can a more detailed log be activated to exclude **wghttp**?

**Comment by zhsj** [comment]
wghttp doesn't support UDP, and there's no plan to support it.

**Comment by XEGARE** [comment]
> wghttp doesn't support UDP, and there's no plan to support it.
OK. I understand
